"""
Hand-picked seed list for the WordPress tryouts scraper.

Each entry is a best-effort guess at a club that probably runs a
WordPress site with tryout info under one of the paths probed by
``scrape_tryouts_wordpress``. The runner never fails on a miss — sites
without a matching tryout page are silently skipped, so the cost of a
wrong guess is one HTTP request.

Grow this list over time. When a scheduled run produces zero rows for
an entry for several seasons, remove it.

HISTORY
-------
April 2026: Backfilled from ``canonical_clubs.website`` (Apr 16, 2026).
After deduping by domain and filtering out directory/aggregator/news
sites (mapquest, maxpreps, hudl, wikipedia, etc.), 861 unique homepages
remain. Quality is mixed — roughly 50-60% point to actual club
websites, the rest are misattributed (hotels, chain facilities,
state associations). The scraper's fail-soft design means wrong
entries cost one HTTP 404 each — no harm beyond runtime.

KNOWN QUALITY LIMITATIONS
-------------------------
  * ~40% of the URLs don't point to a real club homepage. A separate
    canonical_clubs.website cleanup pass would improve signal-to-noise.
  * Club names come from the raw DB field and may be short tokens
    (e.g. "- San Marcos" or "956") rather than canonical names. The
    tryouts writer stores these as-is in club_name_raw; the
    canonical-club linker resolves them to club IDs later.
  * Paths were stripped to homepage URLs — path-specific URLs from
    the DB are not preserved here.

To ADD a site manually:
    1. Visit the club's public website.
    2. Check that ``/tryouts/`` or ``/register/`` returns a page with
       either a date OR a third-party registration link (LeagueApps,
       GotSport, TGS, etc. — captured by extract_registration_links).
    3. Append a ``{"club_name_raw", "website"}`` entry below.
    4. Rerun ``python scraper/run.py --source tryouts-wordpress --dry-run``.
"""

from __future__ import annotations

from typing import Dict, List


TRYOUTS_WORDPRESS_SEED: List[Dict[str, str]] = [
    {'club_name_raw': "- San Marcos", 'website': "https://surgesoccertx.org"},
    {'club_name_raw': "3Rsc", 'website': "https://3rsc.org"},
    {'club_name_raw': "5 Academy", 'website': "https://www.soccer5academy.com"},
    {'club_name_raw': "Abington", 'website': "https://www.abingtonyouthsoccer.org"},
    {'club_name_raw': "Addison", 'website': "http://www.addisonunitedsoccer.org"},
    {'club_name_raw': "Ajax Premier", 'website': "https://wronasoccer.com"},
    {'club_name_raw': "Alabama Rush", 'website': "https://www.alabamarushsoccer.com"},
    {'club_name_raw': "Alameda", 'website': "https://www.sofive.com"},
    {'club_name_raw': "Alaska Rush", 'website': "https://akrush.com"},
    {'club_name_raw': "Albion Atlanta", 'website': "https://albionscatlanta.org"},
    {'club_name_raw': "Albion Delaware", 'website': "https://www.nonprosoccer.com"},
    {'club_name_raw': "Albion Denver", 'website': "https://albionsccolorado.org"},
    {'club_name_raw': "Albion Hurricanes", 'website': "https://houston.beyondthenest.com"},
    {'club_name_raw': "Albion Idaho", 'website': "https://www.albionscidaho.org"},
    {'club_name_raw': "Albion Las Vegas", 'website': "https://albionlvmemorial.com"},
    {'club_name_raw': "Albion Miami", 'website': "https://www.rubellhotels.com"},
    {'club_name_raw': "Albion Santa Monica", 'website': "https://albionscsantamonica.demosphere-secure.com"},
    {'club_name_raw': "Allegiant", 'website': "https://cira.com"},
    {'club_name_raw': "Allentown", 'website': "https://www.allentownyouthsoccer.org"},
    {'club_name_raw': "Almaden", 'website': "https://www.cvysl.org"},
    {'club_name_raw': "America", 'website': "https://socceryouth.com"},
    {'club_name_raw': "Anaheim Futbol", 'website': "https://www.anaheimfc.org"},
    {'club_name_raw': "Anchorage", 'website': "https://www.anchorageyouthsoccer.org"},
    {'club_name_raw': "Annapolis Select Futbol", 'website': "https://selectsoccermd.com"},
    {'club_name_raw': "Ansonia", 'website': "https://www.cityofansonia.com"},
    {'club_name_raw': "Arcola", 'website': "https://www.arcolaillinois.org"},
    {'club_name_raw': "Arden Select", 'website': "https://ardensoccer.com"},
    {'club_name_raw': "Arizona", 'website': "https://azsoccerskills.com"},
    {'club_name_raw': "Arizona Academy", 'website': "https://www.raisingarizonakids.com"},
    {'club_name_raw': "Arkansas Rising", 'website': "https://web.littlerockchamber.com"},
    {'club_name_raw': "Arlington", 'website': "https://www.arlingtoncoedkicks.com"},
    {'club_name_raw': "Arsenal Colorado", 'website': "https://www.soccerfortcollins.org"},
    {'club_name_raw': "As Junior Elite", 'website': "https://www.asjuniorelite.com"},
    {'club_name_raw': "Aspen Hill", 'website': "https://www.aspenhillsoccer.org"},
    {'club_name_raw': "Association", 'website': "https://www.azsoccerassociation.org"},
    {'club_name_raw': "Athlete Institute", 'website': "https://www.ontariosoccer.net"},
    {'club_name_raw': "Atlanta Fire", 'website': "https://www.atlantaunitedsoccer.com"},
    {'club_name_raw': "Atlantic", 'website': "https://atlanticunitedsc.com"},
    {'club_name_raw': "Augusta Arsenal", 'website': "https://www.augustasoccer.com"},
    {'club_name_raw': "Aviators", 'website': "https://sycamoreaviators.org"},
    {'club_name_raw': "Avon", 'website': "https://www.avonsoccerclub.org"},
    {'club_name_raw': "Ayso", 'website': "https://www.aysounitedalabama.org"},
    {'club_name_raw': "Az Inferno", 'website': "https://www.azinfernosoccerclub.net"},
    {'club_name_raw': "Azfc", 'website': "https://www.azfcselect.com"},
    {'club_name_raw': "Baldwin Rush", 'website': "https://perdidobayfc.com"},
    {'club_name_raw': "Ball Masters", 'website': "https://ballmasters.net"},
    {'club_name_raw': "Ballyhoo", 'website': "http://ballyhoosportsacademy.com"},
    {'club_name_raw': "Baltimore Celtic", 'website': "https://baltimoreceltic.com"},
    {'club_name_raw': "Baltimore Stars", 'website': "https://sportsteamhistory.com"},
    {'club_name_raw': "Barca Residency Academy Usa", 'website': "https://barcaresidencyacademyusa.com"},
    {'club_name_raw': "Bartow", 'website': "https://bartowsoccerclub.com"},
    {'club_name_raw': "Batavia", 'website': "https://fcbatavia.com"},
    {'club_name_raw': "Bay Lions Florida", 'website': "https://www.baylionsfloridasoccerclub.com"},
    {'club_name_raw': "Bayshore", 'website': "https://www.bayshoresc.com"},
    {'club_name_raw': "Bayside", 'website': "https://baysidefcfoundation.org"},
    {'club_name_raw': "Bayside Football", 'website': "https://baysidefcsomd.com"},
    {'club_name_raw': "Beach", 'website': "https://beachsoccer.com"},
    {'club_name_raw': "Beachside", 'website': "https://beachsidesoccer.org"},
    {'club_name_raw': "Beacon", 'website': "https://www.beaconsoccerclub.org"},
    {'club_name_raw': "Belmont", 'website': "https://belmontunited.net"},
    {'club_name_raw': "Beltsville Academy", 'website': "https://171312.digitalsports.com"},
    {'club_name_raw': "Bend", 'website': "https://www.bendfctimbers.com"},
    {'club_name_raw': "Bergenfield", 'website': "https://www.bergenfieldunited.com"},
    {'club_name_raw': "Berkeley Heights", 'website': "https://www.bhysc.com"},
    {'club_name_raw': "Berwyn Heights And", 'website': "https://berwynheightshistory.com"},
    {'club_name_raw': "Bethlehem Township", 'website': "https://cblbasketball.org"},
    {'club_name_raw': "Black Watch Premier", 'website': "https://www.sylsoccer.com"},
    {'club_name_raw': "Blacklions", 'website': "https://blsoccerclub.com"},
    {'club_name_raw': "Bloomfield", 'website': "https://www.bloomfieldsoccerclub.com"},
    {'club_name_raw': "Blues", 'website': "https://bluesfc.org"},
    {'club_name_raw': "Boca Orange County", 'website': "https://chsasoccer.demosphere-secure.com"},
    {'club_name_raw': "Boise Timbers", 'website': "https://boisetimbersthorns.org"},
    {'club_name_raw': "Bold Academy", 'website': "https://boldacademy.insiderealestate.com"},
    {'club_name_raw': "Bolton", 'website': "https://www.boltonctsoccer.com"},
    {'club_name_raw': "Bonita Springs Wildcats", 'website': "https://www.bonitaspringswildcats.org"},
    {'club_name_raw': "Boston Bolts", 'website': "https://bostonbolts.com"},
    {'club_name_raw': "Bowie And", 'website': "https://www.dailynews.com"},
    {'club_name_raw': "Boyertown", 'website': "https://www.easternpafootball.com"},
    {'club_name_raw': "Boynton", 'website': "https://www.boyntonknightsfc.com"},
    {'club_name_raw': "Branchburg Travel", 'website': "https://www.branchburgtravelsoccer.org"},
    {'club_name_raw': "Branford", 'website': "https://www.branfordsoccer.org"},
    {'club_name_raw': "Brasil", 'website': "https://brazilworldcupblog.net"},
    {'club_name_raw': "Brave Sporting", 'website': "https://www.bravesc.com"},
    {'club_name_raw': "Bravo", 'website': "http://www.fcbravo.com"},
    {'club_name_raw': "Brea", 'website': "https://www.breasoccer.org"},
    {'club_name_raw': "Brentwood", 'website': "https://brentwoodyouthsoccer.com"},
    {'club_name_raw': "Brewster", 'website': "https://brewsterfc.org"},
    {'club_name_raw': "Bridgeview Academy", 'website': "https://bridgeviewsoccer.com"},
    {'club_name_raw': "Bridgewater Sa", 'website': "https://www.bridgewatersoccer.com"},
    {'club_name_raw': "Bristol", 'website': "https://bristolallheart.com"},
    {'club_name_raw': "Brookfield", 'website': "https://www.brookfieldsoccer.org"},
    {'club_name_raw': "Brooklyn", 'website': "https://www.brooklynforcesoccer.com"},
    {'club_name_raw': "Broomfield", 'website': "https://www.broomfieldsoccerclub.org"},
    {'club_name_raw': "Bryc Academy", 'website': "https://www.brycsoccer.com"},
    {'club_name_raw': "Bsm Elite", 'website': "https://www.bsmelite.com"},
    {'club_name_raw': "Bury", 'website': "https://www.delmarvasportsnetwork.com"},
    {'club_name_raw': "Busa Frederick", 'website': "https://programs.brazilianunited.com"},
    {'club_name_raw': "Bvbia", 'website': "https://www.bvbia-atlanta.com"},
    {'club_name_raw': "By Rachel", 'website': "https://soccerbyrachel.com"},
    {'club_name_raw': "Cali Rise", 'website': "https://www.fusionsc.org"},
    {'club_name_raw': "Camden", 'website': "http://www.camdensoccerclub.org"},
    {'club_name_raw': "Campton", 'website': "https://www.camptonunited.com"},
    {'club_name_raw': "Cantera", 'website': "https://www.canterasoccerclub.com"},
    {'club_name_raw': "Canterbury", 'website': "https://www.cbury.org"},
    {'club_name_raw': "Cape Coral", 'website': "https://capecoralsoccer.com"},
    {'club_name_raw': "Cape Express", 'website': "https://www.capeexpress.com"},
    {'club_name_raw': "Capital", 'website': "https://soccerzonesouthaustin.ezleagues.ezfacility.com"},
    {'club_name_raw': "Caribbiana", 'website': "https://www.caribbianafc.com"},
    {'club_name_raw': "Carolina Core", 'website': "https://carolinacoreyouth.com"},
    {'club_name_raw': "Carolina Velocity", 'website': "https://www.southatlanticpremierleague.com"},
    {'club_name_raw': "Castro Valley", 'website': "https://www.castrovalleysoccer.com"},
    {'club_name_raw': "Catonsville", 'website': "https://www.catonsvillesoccer.com"},
    {'club_name_raw': "Cbf School Boca Raton", 'website': "https://www.cbfschoolboca.com"},
    {'club_name_raw': "Cda Slammers", 'website': "https://cdaslammers.com"},
    {'club_name_raw': "Cedar Stars Academy", 'website': "https://www.cedarstars.com"},
    {'club_name_raw': "Cedar Stars Academy - Monmouth", 'website': "http://njsa.ussoccerda.com"},
    {'club_name_raw': "Cedar Stars Academy North", 'website': "https://www.edpsoccer.com"},
    {'club_name_raw': "Central Brevard", 'website': "https://www.centralbrevardsoccer.com"},
    {'club_name_raw': "Central Cal Aztecs", 'website': "https://www.centralcalaztecs.org"},
    {'club_name_raw': "Central Carroll", 'website': "https://www.centralcarrollsc.com"},
    {'club_name_raw': "Central Coast Surf", 'website': "https://www.centralcoastsurfsoccer.com"},
    {'club_name_raw': "Central Florida", 'website': "https://centralfloridasoccer.com"},
    {'club_name_raw': "Central Jersey Futbol Alliance", 'website': "https://centraljerseyfa.com"},
    {'club_name_raw': "Central Valley", 'website': "https://citysccentralvalley.com"},
    {'club_name_raw': "Central Washington", 'website': "https://www.centralwashingtonsocceracademy.com"},
    {'club_name_raw': "Cfc North", 'website': "https://connecticutfootballclub.demosphere-secure.com"},
    {'club_name_raw': "Cfc South", 'website': "https://www.connecticutfootballclub.com"},
    {'club_name_raw': "Cga Academy", 'website': "https://cgaacademysc.com"},
    {'club_name_raw': "Challenge", 'website': "https://www.challengesoccer.com"},
    {'club_name_raw': "Charles Village", 'website': "https://www.charlesvillagerec.org"},
    {'club_name_raw': "Charlotte Development Academy", 'website': "https://www.cdasoccernc.com"},
    {'club_name_raw': "Chattanooga Red Wolves", 'website': "https://www.chattanoogaredwolves-sc.com"},
    {'club_name_raw': "Chelsea Piers", 'website': "https://teams.chelseapiersct.com"},
    {'club_name_raw': "Cherry Hill", 'website': "https://www.cherryhillfcsoccer.com"},
    {'club_name_raw': "Chesapeake Ninjas", 'website': "https://www.chesapeakeninjas.org"},
    {'club_name_raw': "Cheshire", 'website': "https://www.cheshiresoccerclub.org"},
    {'club_name_raw': "Cheshire Academy", 'website': "https://cheshireacademy.org"},
    {'club_name_raw': "Chestnut Hill", 'website': "https://www.chestnuthillsc.com"},
    {'club_name_raw': "Cheverly", 'website': "https://cheverlysoccerclub.org"},
    {'club_name_raw': "Chicago", 'website': "https://www.chicagocitysoccerclub.com"},
    {'club_name_raw': "Chicago Blast", 'website': "https://www.chicagoblastsoccer.com"},
    {'club_name_raw': "Chicago Empire", 'website': "https://www.chicagoempirefc.com"},
    {'club_name_raw': "Chicago Inter", 'website': "https://www.chicagointersoccer.com"},
    {'club_name_raw': "Chivas", 'website': "https://www.flashscoreusa.com"},
    {'club_name_raw': "Chugiak", 'website': "https://www.chugiaksoccerclub.com"},
    {'club_name_raw': "Chula Vista", 'website': "https://cityscchulavista.com"},
    {'club_name_raw': "Churchville", 'website': "https://www.churchvillesoccerclub.com"},
    {'club_name_raw': "Cifa", 'website': "https://www.cifainternational.org"},
    {'club_name_raw': "Cipriani Accademia", 'website': "https://www.vysa.com"},
    {'club_name_raw': "Cityzens", 'website': "https://cityzensfc.teamsnapsites.com"},
    {'club_name_raw': "Claremont Stars", 'website': "https://www.leaguelineup.com"},
    {'club_name_raw': "Clark", 'website': "https://www.clarksoccerclub.org"},
    {'club_name_raw': "Clarkstown", 'website': "https://www.clarkstownsc.org"},
    {'club_name_raw': "Classic", 'website': "https://azarsenalsc_academy.demosphere-secure.com"},
    {'club_name_raw': "Classics Elite", 'website': "https://www.classicselite.com"},
    {'club_name_raw': "Clermont Football", 'website': "http://www.gcfsoccer.com"},
    {'club_name_raw': "Cleveland Force", 'website': "https://www.clevelandforcesc.com"},
    {'club_name_raw': "Clifton", 'website': "https://www.cliftonsoccer.org"},
    {'club_name_raw': "Clinton And", 'website': "https://clintonjets.org"},
    {'club_name_raw': "Clovis Crossfire", 'website': "https://cloviscrossfire.com"},
    {'club_name_raw': "Coast Fa", 'website': "https://www.coastfa.com"},
    {'club_name_raw': "Coastal Rush", 'website': "https://www.coastalrushsoccer.com"},
    {'club_name_raw': "Cocalico", 'website': "https://cysc.org"},
    {'club_name_raw': "Coerfontaine", 'website': "https://coerfontainefc.com"},
    {'club_name_raw': "Cohansey", 'website': "https://www.cohanseysoccer.org"},
    {'club_name_raw': "Colchester", 'website': "https://www.colchestersoccer.org"},
    {'club_name_raw': "Coliseum", 'website': "https://soccercoliseum.com"},
    {'club_name_raw': "Colo Colo Academy Usa", 'website': "https://division1.upsl.com"},
    {'club_name_raw': "Colonial", 'website': "https://www.colonialsd.org"},
    {'club_name_raw': "Colorado Edge", 'website': "https://birdeye.com"},
    {'club_name_raw': "Colorado Rapids", 'website': "https://rapidsyouthsoccer.org"},
    {'club_name_raw': "Colorado Rush", 'website': "https://www.coloradorush.com"},
    {'club_name_raw': "Columbus", 'website': "https://www.columbusunited.org"},
    {'club_name_raw': "Columbus Force", 'website': "https://www.columbusforcesoccer.com"},
    {'club_name_raw': "Community", 'website': "https://www.communitysoccerclub.com"},
    {'club_name_raw': "Community First", 'website': "https://www.communityfirstsoccer.com"},
    {'club_name_raw': "Community Outreach", 'website': "https://community-outreach.org"},
    {'club_name_raw': "Complete Athlete Training", 'website': "https://completeathletictraining.com"},
    {'club_name_raw': "Concord Sa", 'website': "https://www.concordsoccer.com"},
    {'club_name_raw': "Concorde Fire Premier", 'website': "https://prepsoccer.com"},
    {'club_name_raw': "Congaree Rapid", 'website': "https://www.scsoccer.com"},
    {'club_name_raw': "Connecticut", 'website': "https://www.gzs-usa.com"},
    {'club_name_raw': "Connection", 'website': "https://www.illinoisyouthsoccer.org"},
    {'club_name_raw': "Copa Academy", 'website': "https://www.fccopa.com"},
    {'club_name_raw': "Coppermine", 'website': "https://www.copperminesoccer.com"},
    {'club_name_raw': "Cosc", 'website': "https://www.coscsoccer.org"},
    {'club_name_raw': "Cosmo Stars", 'website': "https://cosmostars.net"},
    {'club_name_raw': "Council Rock", 'website': "https://www.daffy.org"},
    {'club_name_raw': "Cranford", 'website': "https://www.cranfordsoccer.com"},
    {'club_name_raw': "Croatian Eagles", 'website': "https://www.croatianeagles.com"},
    {'club_name_raw': "Crusa", 'website': "https://www.fcbucks.com"},
    {'club_name_raw': "Ct Rush", 'website': "https://www.northeastrush.com"},
    {'club_name_raw': "Cyclones", 'website': "https://cyclones.capecoralsoccer.com"},
    {'club_name_raw': "Cys Tampa", 'website': "https://www.cystampa.org"},
    {'club_name_raw': "Dallas Red", 'website': "https://www.ebay.com"},
    {'club_name_raw': "Dallas Texans", 'website': "https://dallastexans.com"},
    {'club_name_raw': "Dallas Texans Academy", 'website': "https://fwyouthsoccer.org"},
    {'club_name_raw': "Dallas White", 'website': "http://www.theathleticsdepartment.com"},
    {'club_name_raw': "Danubia", 'website': "https://feversc.com"},
    {'club_name_raw': "Davis Legacy", 'website': "https://davislegacysoccer.org"},
    {'club_name_raw': "Dayton", 'website': "https://www.fcdayton.org"},
    {'club_name_raw': "Dc Sports", 'website': "https://www.dcsportsfl.com"},
    {'club_name_raw': "Dc Way Academy", 'website': "https://dcwayacademy.org"},
    {'club_name_raw': "Dcsc", 'website': "https://playpass.com"},
    {'club_name_raw': "Decatur", 'website': "https://www.decatursoccer.com"},
    {'club_name_raw': "Delaware", 'website': "https://delaware-football-club.wheree.com"},
    {'club_name_raw': "Delaware Football", 'website': "https://www.delawarefootballleague.com"},
    {'club_name_raw': "Delmarva Rush", 'website': "https://www.delmarvarush.com"},
    {'club_name_raw': "Delran", 'website': "https://www.delranfc.com"},
    {'club_name_raw': "Deltona", 'website': "https://deltona-youth-soccer-club.wheree.com"},
    {'club_name_raw': "Den Of Lions", 'website': "https://denoflions.com"},
    {'club_name_raw': "Deportivo Arizona", 'website': "https://www.fcdeportivoaz.com"},
    {'club_name_raw': "Detroit", 'website': "https://www.detcityfc.com"},
    {'club_name_raw': "Diablo Valley", 'website': "https://www.diablovalleyfc.com"},
    {'club_name_raw': "Diablo Valley Futbol", 'website': "https://mtdiablomustangsoccer.com"},
    {'club_name_raw': "District 6", 'website': "https://d6soccer.org"},
    {'club_name_raw': "District Of Columbia Football", 'website': "https://www.districtofcolumbiafc.com"},
    {'club_name_raw': "Dme Academy, Sarasota", 'website': "https://dmeacademysarasota.com"},
    {'club_name_raw': "Dmv Gaindes", 'website': "https://sadmvgaindes.org"},
    {'club_name_raw': "Doca Futebol Academy", 'website': "https://ussoccerparent.com"},
    {'club_name_raw': "Dover Futbol", 'website': "https://www.doversportsclub.com"},
    {'club_name_raw': "Dribbling", 'website': "https://achievesports.com"},
    {'club_name_raw': "Dublin", 'website': "https://www.dublinsoccer.org"},
    {'club_name_raw': "Dutchmen", 'website': "https://www.fcdutchmen.com"},
    {'club_name_raw': "Dv7 Ny", 'website': "https://www.dv7soccer.com"},
    {'club_name_raw': "Dynamos", 'website': "https://azscore.com"},
    {'club_name_raw': "Eagles Training Center", 'website': "https://michaelgraves.com"},
    {'club_name_raw': "Easley", 'website': "https://www.redandblack.com"},
    {'club_name_raw': "East Brunswick", 'website': "https://ebsoccer.com"},
    {'club_name_raw': "East Fishkill", 'website': "https://efsc.net"},
    {'club_name_raw': "East Florida", 'website': "https://eastfloridaunited.com"},
    {'club_name_raw': "East Hanover", 'website': "https://www.easthanoversoccer.org"},
    {'club_name_raw': "East Ramapo", 'website': "http://eastramaposoccerclub.com"},
    {'club_name_raw': "East Windsor", 'website': "http://www.sportsfieldsusa.com"},
    {'club_name_raw': "Eastern Pike", 'website': "https://www.easternpikesoccer.com"},
    {'club_name_raw': "Eastside Timbers", 'website': "https://zaubee.com"},
    {'club_name_raw': "Ebbetts Pass Gold", 'website': "https://www.epysl.org"},
    {'club_name_raw': "Ecusta", 'website': "https://trailsidebrews.com"},
    {'club_name_raw': "Edina", 'website': "https://www.edinasoccerclub.com"},
    {'club_name_raw': "Egg Harbor Township", 'website': "https://www.ehtsoccerclub.com"},
    {'club_name_raw': "El Camino", 'website': "https://www.ecfcsalinas.com"},
    {'club_name_raw': "El Paso Locomotive", 'website': "https://www.eplocomotivefc.com"},
    {'club_name_raw': "El Paso Surf", 'website': "https://elpasosurf.elitesoccerclubs.com"},
    {'club_name_raw': "Elite", 'website': "https://www.idahoelitesoccer.com"},
    {'club_name_raw': "Elite Arizona", 'website': "https://elitearizonaathletes.com"},
    {'club_name_raw': "Elite Development Academy", 'website': "http://socaleda.com"},
    {'club_name_raw': "Elite Kickers", 'website': "https://elitekickers.com"},
    {'club_name_raw': "Elite Plainfield", 'website': "https://www.ballertv.com"},
    {'club_name_raw': "Elite Strikers", 'website': "https://elitestrikersfc.org"},
    {'club_name_raw': "Elitevision", 'website': "https://www.elitevisionathletics.com"},
    {'club_name_raw': "Elizabeth", 'website': "http://www.elizabethsoccer.com"},
    {'club_name_raw': "Elk Grove", 'website': "https://elkgrovesoccer.com"},
    {'club_name_raw': "Ellicott", 'website': "https://ellicottcitysc.org"},
    {'club_name_raw': "Elmwood Park Crew", 'website': "https://www.epcrewsoccer.com"},
    {'club_name_raw': "Elvaton Elite", 'website': "https://www.activekids.com"},
    {'club_name_raw': "Ephrata", 'website': "https://ephratasoccer.com"},
    {'club_name_raw': "Epic", 'website': "https://epicsoccerclub.com"},
    {'club_name_raw': "Eristars", 'website': "https://eristarssportsclub.teamsnapsites.com"},
    {'club_name_raw': "Eugene Metro", 'website': "https://emfc.org"},
    {'club_name_raw': "Europa Lions", 'website': "https://www.europalionsfc.com"},
    {'club_name_raw': "Fa Euro New York", 'website': "https://www.faeuro.com"},
    {'club_name_raw': "Fairfax Police", 'website': "https://www.fpycsports.com"},
    {'club_name_raw': "Fallston", 'website': "https://fallstonrec.com"},
    {'club_name_raw': "Farmingdale", 'website': "https://www.farmingdalesoccer.com"},
    {'club_name_raw': "Farmington", 'website': "https://www.farmingtonhighboyssoccer.com"},
    {'club_name_raw': "Fcgb Center Of Excellence", 'website': "https://www.fcgbcoe.org"},
    {'club_name_raw': "Fci Academy", 'website': "https://www.fciacademy.org"},
    {'club_name_raw': "Fd Football", 'website': "https://www.fdfootballclub.com"},
    {'club_name_raw': "Fhfc", 'website': "https://marltonfieldhouse.ezleagues.ezfacility.com"},
    {'club_name_raw': "First Coast Futsal Academy", 'website': "https://www.firstcoastfutsal.com"},
    {'club_name_raw': "Fl Premier", 'website': "https://www.swflpremierfc.com"},
    {'club_name_raw': "Fla Pro Academy", 'website': "https://www.flasoccer.com"},
    {'club_name_raw': "Flagstaff", 'website': "https://www.englishsoccer.com"},
    {'club_name_raw': "Flight School", 'website': "https://flightschool.leaguesuite.com"},
    {'club_name_raw': "Florham Park", 'website': "https://www.thefootballacademynj.com"},
    {'club_name_raw': "Florida", 'website': "https://www.miramarpal.org"},
    {'club_name_raw': "Florida Celtic", 'website': "https://www.floridaceltic.com"},
    {'club_name_raw': "Florida Hawks Futbol", 'website': "https://floridahawksfc.sportngin.com"},
    {'club_name_raw': "Florida Keys", 'website': "https://floridakeyssoccer.com"},
    {'club_name_raw': "Florida Kraze", 'website': "https://floridakrazekrush.com"},
    {'club_name_raw': "Florida Prime", 'website': "https://floridaprimesoccercup.net"},
    {'club_name_raw': "Florida Royal", 'website': "https://floridaroyalfc.com"},
    {'club_name_raw': "Florida Tropics Academy", 'website': "https://tropicsacademyfl.com"},
    {'club_name_raw': "Follow", 'website': "https://followsoccer.com"},
    {'club_name_raw': "Folsom Lake Surf", 'website': "https://folsomlakesurf.org"},
    {'club_name_raw': "Foothill Storm", 'website': "https://foothillstormsc.org"},
    {'club_name_raw': "Force", 'website': "https://www.clsf.org"},
    {'club_name_raw': "Fort Myers Beach", 'website': "https://fmbsoccer.com"},
    {'club_name_raw': "Foundation Academy", 'website': "https://www.foundationacademy.net"},
    {'club_name_raw': "Founders", 'website': "https://www.foundersathletics.org"},
    {'club_name_raw': "Franklin Township", 'website': "https://www.franklinsoccer.com"},
    {'club_name_raw': "Frederick", 'website': "https://cityscfrederick.com"},
    {'club_name_raw': "Freedom", 'website': "https://azfreedombaseballclub.com"},
    {'club_name_raw': "Fresno Academy", 'website': "https://www.fcfresnoacademy.com"},
    {'club_name_raw': "Furman", 'website': "https://gseagles.com"},
    {'club_name_raw': "Futbol Total Academy Nj", 'website': "https://futboltotalacademynj.com"},
    {'club_name_raw': "Futboltech", 'website': "https://www.futboltechsoccer.com"},
    {'club_name_raw': "Future", 'website': "https://future-fc.org"},
    {'club_name_raw': "Galaxy", 'website': "https://members.naperville.net"},
    {'club_name_raw': "Gardendale", 'website': "https://www.cityofgardendale.com"},
    {'club_name_raw': "Georgia Athletic", 'website': "https://www.georgiaathleticsc.com"},
    {'club_name_raw': "Georgia Impact", 'website': "https://canton.macaronikid.com"},
    {'club_name_raw': "German American Kickers", 'website': "https://gakickers.webs.com"},
    {'club_name_raw': "Germantown Impact", 'website': "https://www.germantownimpact.com"},
    {'club_name_raw': "Germantown Legends", 'website': "https://www.germantownlegendssoccer.com"},
    {'club_name_raw': "Gfi Academy", 'website': "https://gfiacademy.com"},
    {'club_name_raw': "Glastonbury Hartwell", 'website': "http://www.glastonburysoccer.org"},
    {'club_name_raw': "Glen Celtic America", 'website': "https://www.glencelticamericafc.com"},
    {'club_name_raw': "Glen Rock", 'website': "https://glenrockunited.org"},
    {'club_name_raw': "Glen Rock Shooting Stars", 'website': "https://www.glenrockshootingstars.org"},
    {'club_name_raw': "Global Academy", 'website': "https://fcbayern.com"},
    {'club_name_raw': "Goshen", 'website': "https://www.goshensoccerclub.org"},
    {'club_name_raw': "Grassroots Academy", 'website': "https://www.murraysoccer.com"},
    {'club_name_raw': "Great Falls Reston", 'website': "https://www.gfrsoccerclub.org"},
    {'club_name_raw': "Greenburgh", 'website': "https://www.greenburghunited.com"},
    {'club_name_raw': "Gretna Elite Academy", 'website': "https://usclubsoccer.org"},
    {'club_name_raw': "Grove", 'website': "https://www.grovesocceracademy.com"},
    {'club_name_raw': "Hamilton", 'website': "https://www.hamiltonwildcatsfc.com"},
    {'club_name_raw': "Hamilton Elite", 'website': "https://www.hamiltonelitefc.com"},
    {'club_name_raw': "Harborfields", 'website': "https://www.harborfieldssoccerclub.com"},
    {'club_name_raw': "Harford", 'website': "https://oldlinefc.com"},
    {'club_name_raw': "Harleysville", 'website': "https://www.harleysvillefc.org"},
    {'club_name_raw': "Harrison", 'website': "https://www.harrisonhoyasoccer.com"},
    {'club_name_raw': "Harrison Futbol", 'website': "https://www.harrisonfutbolclub.com"},
    {'club_name_raw': "Hattiesburg", 'website': "https://www.usmsoccercamps.com"},
    {'club_name_raw': "Havasu Lions", 'website': "https://www.havasulions.com"},
    {'club_name_raw': "Hempstead Eoc", 'website': "https://www.hempsteadeocsoccerclub.org"},
    {'club_name_raw': "Hereford", 'website': "https://www.herefordsoccerclub.com"},
    {'club_name_raw': "Herndon", 'website': "https://www.herndonyouthsoccer.org"},
    {'club_name_raw': "Hex Dominion", 'website': "https://www.padominionfc.org"},
    {'club_name_raw': "Hicksville", 'website': "https://www.hicksvillesoccerclub.com"},
    {'club_name_raw': "Highland", 'website': "https://udisc.com"},
    {'club_name_raw': "Hillsborough", 'website': "https://hillsboroughsoccerclub.com"},
    {'club_name_raw': "Hobe Sound", 'website': "https://www.hobesoundsoccer.com"},
    {'club_name_raw': "Hoboken", 'website': "https://www.hobokenadultsoccer.com"},
    {'club_name_raw': "Hollywood", 'website': "https://www.hollywoodfc.com"},
    {'club_name_raw': "Holmdel", 'website': "https://holmdelfc.org"},
    {'club_name_raw': "Hoover", 'website': "https://www.hoovervestaviasoccer.com"},
    {'club_name_raw': "Horsham", 'website': "https://www.horshamsoccer.com"},
    {'club_name_raw': "Hotspur", 'website': "https://www.tottenhamhotspur.com"},
    {'club_name_raw': "Houston Surf", 'website': "https://www.houstonsurfsc.com"},
    {'club_name_raw': "Houstonians", 'website': "https://houstoniansfc.org"},
    {'club_name_raw': "Howell", 'website': "https://www.howellsoccerclub.com"},
    {'club_name_raw': "Htx S", 'website': "https://htxsoccer.com"},
    {'club_name_raw': "Hunter", 'website': "https://issuu.com"},
    {'club_name_raw': "Hunter'S Creek", 'website': "https://ocss-hunterscreek.com"},
    {'club_name_raw': "Huntington Inter", 'website': "https://www.huntingtonfc.com"},
    {'club_name_raw': "Idaho Inferno", 'website': "https://idahoinfernosc.org"},
    {'club_name_raw': "Idaho Juniors", 'website': "https://www.idahojuniorsfc.com"},
    {'club_name_raw': "Idaho Legends", 'website': "https://www.idaholegendssoccerclub.com"},
    {'club_name_raw': "Idaho Rush", 'website': "https://www.idahorush.com"},
    {'club_name_raw': "Idaho Storm", 'website': "https://idahostormsoccer.com"},
    {'club_name_raw': "Idaho Surf", 'website': "https://www.idahosurfsc.org"},
    {'club_name_raw': "Iffc", 'website': "https://www.waze.com"},
    {'club_name_raw': "Illinois Cardinals", 'website': "https://1440wrok.com"},
    {'club_name_raw': "Illinois Magic", 'website': "https://www.illinoismagicfc.com"},
    {'club_name_raw': "Imagination Academy", 'website': "https://imaginationsoccer.com"},
    {'club_name_raw': "Impact", 'website': "https://www.impactcityfc.com"},
    {'club_name_raw': "Independent", 'website': "http://blast05g.clubindependent.org"},
    {'club_name_raw': "Indiana Elite", 'website': "https://www.indianaelitefc.com"},
    {'club_name_raw': "Indie Chicas", 'website': "https://indiechicas.org"},
    {'club_name_raw': "Indy Eleven Pro Academy", 'website': "https://www.indyelevenproacademy.com"},
    {'club_name_raw': "Indy Eleven Spirit", 'website': "https://www.indyelevenspirit.org"},
    {'club_name_raw': "Inter Atlanta", 'website': "https://www.interatlantafc.com"},
    {'club_name_raw': "Inter Ct", 'website': "https://www.interctfc.com"},
    {'club_name_raw': "Inter Nj", 'website': "https://www.njplaysports.com"},
    {'club_name_raw': "Inter-", 'website': "https://www.interunitedsoccer.org"},
    {'club_name_raw': "International", 'website': "https://www.lakelandunitedfc.com"},
    {'club_name_raw': "Iowa", 'website': "https://www.soccershots.com"},
    {'club_name_raw': "Iron Valley", 'website': "https://www.ironvalley.com"},
    {'club_name_raw': "Ironbound", 'website': "https://www.tapinto.net"},
    {'club_name_raw': "Itasca Park District", 'website': "https://itasca-park-district.com-place.com"},
    {'club_name_raw': "J Petrov Academy", 'website': "https://jpetrovacademy.com"},
    {'club_name_raw': "Ja Elite", 'website': "https://www.leagueathletics.com"},
    {'club_name_raw': "Jackson", 'website': "https://www.jacksonsc.org"},
    {'club_name_raw': "Jackson Hole", 'website': "https://www.jacksonholeyouthsoccer.org"},
    {'club_name_raw': "Jacksonville", 'website': "https://boldcitysoccer.com"},
    {'club_name_raw': "Jaguars", 'website': "https://jaguarsunitedfc.com"},
    {'club_name_raw': "Jersey Association", 'website': "https://www.miniaturejerseyassociation.com"},
    {'club_name_raw': "Jersey Knights", 'website': "https://jersey-knights-soccer-complex.sportsgrounds.us.com"},
    {'club_name_raw': "Jersey Shore Boca Jr", 'website': "http://www.jerseyshoreboca.com"},
    {'club_name_raw': "Jersey South", 'website': "https://jerseysouthfc.com"},
    {'club_name_raw': "Joga Futebol", 'website': "https://www.jogafc.com"},
    {'club_name_raw': "Junior Warriors", 'website': "https://www.juniorwarriorssc.com"},
    {'club_name_raw': "Just One", 'website': "https://justonesoccer.org"},
    {'club_name_raw': "Juventus", 'website': "https://www.dandb.com"},
    {'club_name_raw': "Juventus Academy Dc Metro", 'website': "https://www.juventusdcmetro.com"},
    {'club_name_raw': "Juventus Academy Miami", 'website': "https://jacademymiami.com"},
    {'club_name_raw': "Juventus Academy Ny", 'website': "https://juventusny.com"},
    {'club_name_raw': "Kc Fusion", 'website': "https://www.kcfusion.com"},
    {'club_name_raw': "Kearny Thistle", 'website': "https://www.kearnythistleunited.com"},
    {'club_name_raw': "Kent County Parks And Rec", 'website': "https://delawarescene.com"},
    {'club_name_raw': "Key Biscayne", 'website': "https://keybiscaynesoccerclub.com"},
    {'club_name_raw': "Keystone Athletic", 'website': "https://www.keystoneathletic.com"},
    {'club_name_raw': "Kingman", 'website': "https://kingmansoccer.com"},
    {'club_name_raw': "Kutztown", 'website': "https://www.kutztownsc.com"},
    {'club_name_raw': "La Academia", 'website': "https://socceracademia.com"},
    {'club_name_raw': "La Breakers", 'website': "https://realsoccerblog.com"},
    {'club_name_raw': "Lacey", 'website': "https://www.laceysoccer.com"},
    {'club_name_raw': "Lafayette", 'website': "https://goredbirds.com"},
    {'club_name_raw': "Laguna", 'website': "https://premier.upsl.com"},
    {'club_name_raw': "Laguna Beach Football", 'website': "https://www.lagunabeachindy.com"},
    {'club_name_raw': "Lake", 'website': "https://lakecountysportscenter.com"},
    {'club_name_raw': "Lake Gaston Association", 'website': "https://www.lgancva.com"},
    {'club_name_raw': "Lake Worth Sharks", 'website': "https://www.lakeworthshark.com"},
    {'club_name_raw': "Lakeville", 'website': "https://www.lakevillesoccer.org"},
    {'club_name_raw': "Lamorinda", 'website': "https://www.lamorindasc.com"},
    {'club_name_raw': "Lancaster", 'website': "https://lancasterinferno.com"},
    {'club_name_raw': "Langhorne Neshaminy", 'website': "https://langhornesoccer.org"},
    {'club_name_raw': "Lase Inc", 'website': "https://www.lasesoccer.com"},
    {'club_name_raw': "Laurel", 'website': "https://www.laurelstormsoccer.org"},
    {'club_name_raw': "Lebanon", 'website': "https://ctfaire.com"},
    {'club_name_raw': "Ledyard", 'website': "https://unitedsocceracademy.com"},
    {'club_name_raw': "Leg-A-Z", 'website': "https://legazsoccer.net"},
    {'club_name_raw': "Legacy", 'website': "https://www.legacysoccerclub.com"},
    {'club_name_raw': "Legends Michigan", 'website': "https://www.lyonfcsoccer.com"},
    {'club_name_raw': "Legends San Diego", 'website': "https://www.legendsfc.net"},
    {'club_name_raw': "Legion Futbol", 'website': "https://legionfutbolclub.com"},
    {'club_name_raw': "Lehigh Valley", 'website': "https://www.lehighvalleylive.com"},
    {'club_name_raw': "Lexington Sporting", 'website': "https://www.kentucky.com"},
    {'club_name_raw': "Liberty", 'website': "https://www.wfmz.com"},
    {'club_name_raw': "Lightning", 'website': "https://www.afclightning.org"},
    {'club_name_raw': "Lions", 'website': "https://coachbricesoccer.com"},
    {'club_name_raw': "Little Haiti Football", 'website': "https://littlehaiti-fc.org"},
    {'club_name_raw': "Liverpool", 'website': "https://www.clevelandmemory.org"},
    {'club_name_raw': "Los Gatos", 'website': "https://www.soccerclublg.com"},
    {'club_name_raw': "Lou Fusz Athletic", 'website': "https://www.loufuszathletic.com"},
    {'club_name_raw': "Loudoun", 'website': "https://www.leesburgfc.com"},
    {'club_name_raw': "Lowcountry Rush", 'website': "https://www.lowcorush.com"},
    {'club_name_raw': "Lower Merion", 'website': "https://www.lmsd.org"},
    {'club_name_raw': "Luciano Emilio", 'website': "https://www.lescinternazionale.com"},
    {'club_name_raw': "Lyme Old Lyme", 'website': "https://www.lolsc.com"},
    {'club_name_raw': "Lyndhurst", 'website': "https://www.lyndhurstsoccer.com"},
    {'club_name_raw': "Macon", 'website': "https://www.teescamps.com"},
    {'club_name_raw': "Madison", 'website': "https://www.madisonfutbol.com"},
    {'club_name_raw': "Madison 56Ers", 'website': "https://madison56ers.org"},
    {'club_name_raw': "Magnus", 'website': "https://magnusfc.sportngin.com"},
    {'club_name_raw': "Mako", 'website': "https://mako-soccer-club-inc.wheree.com"},
    {'club_name_raw': "Malvern", 'website': "https://www.malvernprep.org"},
    {'club_name_raw': "Manalapan", 'website': "https://www.manalapansoccerclub.com"},
    {'club_name_raw': "Manasota", 'website': "https://www.msrafl.org"},
    {'club_name_raw': "Manassas", 'website': "https://www.msclions.com"},
    {'club_name_raw': "Manhattan", 'website': "https://www.manhattansc.org"},
    {'club_name_raw': "Manhattan Kickers", 'website': "http://www.manhattankickersfc.com"},
    {'club_name_raw': "Manitou", 'website': "https://www.eventeny.com"},
    {'club_name_raw': "Manta", 'website': "https://mantasoccer.com"},
    {'club_name_raw': "Maple Shade", 'website': "https://www.mapleshadesoccer.net"},
    {'club_name_raw': "Margate", 'website': "https://www.margatefl.com"},
    {'club_name_raw': "Maricopa", 'website': "https://www.active.com"},
    {'club_name_raw': "Marlton", 'website': "https://www.marltonreccouncil.org"},
    {'club_name_raw': "Maroons", 'website': "https://www.maroonssoccer.com"},
    {'club_name_raw': "Maryland International", 'website': "https://soccermi.com"},
    {'club_name_raw': "Maryland Rush", 'website': "https://www.marylandrush.com"},
    {'club_name_raw': "Mason Dixon", 'website': "https://masondixonsoccer.com"},
    {'club_name_raw': "Match Fit Surf", 'website': "https://www.matchfitsurf.com"},
    {'club_name_raw': "Match Fit Surf - South Jersey", 'website': "https://www.rusafc.com"},
    {'club_name_raw': "Medford", 'website': "https://www.medfordsoccerclub.com"},
    {'club_name_raw': "Medford Strikers", 'website': "https://medfordstrikers.com"},
    {'club_name_raw': "Mercer", 'website': "http://www.mercermensoccer.net"},
    {'club_name_raw': "Meriden", 'website': "https://www.meridensoccerclub.org"},
    {'club_name_raw': "Metro Alliance", 'website': "https://metroalliancefc.com"},
    {'club_name_raw': "Miami Breakers", 'website': "https://www.miamibreakersfc.com"},
    {'club_name_raw': "Miami Premier", 'website': "http://www.miamipremiersoccer.com"},
    {'club_name_raw': "Michigan Burn", 'website': "https://www.soccerfieldmap.com"},
    {'club_name_raw': "Michigan Jaguars", 'website': "https://michiganjaguarsfc.com"},
    {'club_name_raw': "Michigan Stars Elite", 'website': "https://www.michiganstarselite.com"},
    {'club_name_raw': "Middle Country", 'website': "https://www.mccsoccer.org"},
    {'club_name_raw': "Middletown", 'website': "https://middletownsoccer.net"},
    {'club_name_raw': "Mifflin County", 'website': "https://hallerent.com"},
    {'club_name_raw': "Milford", 'website': "https://www.newmilfordsoccer.com"},
    {'club_name_raw': "Millburn", 'website': "https://millburnsoccer.com"},
    {'club_name_raw': "Minneapolis", 'website': "https://grayducks.com"},
    {'club_name_raw': "Minnesota Thunder", 'website': "https://mnthunderacademy.org"},
    {'club_name_raw': "Miramar Optimist", 'website': "https://miramaroptimistclub.com"},
    {'club_name_raw': "Mississippi Rush", 'website': "https://www.jacksonfc.com"},
    {'club_name_raw': "Missouri Rush", 'website': "https://missouri-rush-soccer-club.wheree.com"},
    {'club_name_raw': "Monmouth", 'website': "https://www.monmouthunitedsoccer.com"},
    {'club_name_raw': "Montana Surf", 'website': "https://montanasurf.org"},
    {'club_name_raw': "Montclair", 'website': "https://www.montclairsoccer.com"},
    {'club_name_raw': "Montgomery", 'website': "https://www.alabamafcsouth.org"},
    {'club_name_raw': "Montgomery Travel", 'website': "https://www.montgomerysoccer.org"},
    {'club_name_raw': "Montverde", 'website': "https://www.montverde.org"},
    {'club_name_raw': "Montville", 'website': "https://www.montvillesoccer.org"},
    {'club_name_raw': "Moriches", 'website': "https://morichesyouth.org"},
    {'club_name_raw': "Morris Elite", 'website': "https://morriselitesoccer.com"},
    {'club_name_raw': "Mount Laurel", 'website': "https://www.mlusoccer.org"},
    {'club_name_raw': "Mountainside", 'website': "https://www.mountainsidesocceracademy.com"},
    {'club_name_raw': "Mundelein Lions", 'website': "https://yssl.org"},
    {'club_name_raw': "Mustang", 'website': "https://youthsportsleaders.com"},
    {'club_name_raw': "Mvla", 'website': "https://www.mvlasc.org"},
    {'club_name_raw': "Nampa Premier", 'website': "https://tursisocceridaho.com"},
    {'club_name_raw': "Napa", 'website': "https://napasportsoccerclub.org"},
    {'club_name_raw': "Naples", 'website': "https://www.fcnaples.com"},
    {'club_name_raw': "Naples Elite", 'website': "https://napleselitesoccer.com"},
    {'club_name_raw': "Nasa", 'website': "https://www.nasatophat.com"},
    {'club_name_raw': "Nashville", 'website': "https://www.nashfc.org"},
    {'club_name_raw': "Nationals", 'website': "https://www.nationalssoccer.com"},
    {'club_name_raw': "Nationals Union", 'website': "https://union.nationalssoccer.com"},
    {'club_name_raw': "Nazareth", 'website': "https://www.nazarethacademyhs.org"},
    {'club_name_raw': "Nc Courage", 'website': "https://www.nccourage.com"},
    {'club_name_raw': "Nca Tiger'S", 'website': "https://ncatigersfc.com"},
    {'club_name_raw': "Ncfc Academy", 'website': "https://www.ncfcacademy.com"},
    {'club_name_raw': "Neconn", 'website': "https://www.neconn.org"},
    {'club_name_raw': "Nesa", 'website': "https://www.nesasoccer.com"},
    {'club_name_raw': "Neshanic", 'website': "https://www.fcneshanic.com"},
    {'club_name_raw': "Nether", 'website': "https://phillysoccerpage.net"},
    {'club_name_raw': "New Britain", 'website': "https://www.ussportscamps.com"},
    {'club_name_raw': "New Brunswick", 'website': "https://www.soccernb.org"},
    {'club_name_raw': "New Canaan", 'website': "https://newcanaanchamber.com"},
    {'club_name_raw': "New England", 'website': "https://www.revolutionsoccer.net"},
    {'club_name_raw': "New England Force", 'website': "https://newenglandforce.com"},
    {'club_name_raw': "New England Surf", 'website': "https://newenglandsurf.com"},
    {'club_name_raw': "New Fairfield", 'website': "https://lubussoccer.com"},
    {'club_name_raw': "New Haven", 'website': "https://www.psgacademyusacamp.com"},
    {'club_name_raw': "New Hyde Park Wildcats", 'website': "https://nhpwildcats.org"},
    {'club_name_raw': "New Jersey Legacy", 'website': "https://www.njlegacyfc.com"},
    {'club_name_raw': "New Jersey Rush", 'website': "https://www.njrush.com"},
    {'club_name_raw': "New Jersey Surf", 'website': "https://newjerseysurf.com"},
    {'club_name_raw': "New London", 'website': "http://www.eteamz.com"},
    {'club_name_raw': "New York", 'website': "https://www.nycfooty.com"},
    {'club_name_raw': "Newton", 'website': "https://www.newtonsoccer.org"},
    {'club_name_raw': "Next Level", 'website': "https://www.nextlevelsoccer.com"},
    {'club_name_raw': "Niskayuna", 'website': "https://niskayunasoccerclub.org"},
    {'club_name_raw': "Nj Blaze", 'website': "https://www.njblazesa.com"},
    {'club_name_raw': "Nj Nationals", 'website': "https://www.njnationals.com"},
    {'club_name_raw': "Nj Santos", 'website': "https://www.njsantosrush.com"},
    {'club_name_raw': "Nj Stallions", 'website': "https://www.njstallions.com"},
    {'club_name_raw': "Nj14", 'website': "https://nj14soccerclub.com"},
    {'club_name_raw': "Nlsa", 'website': "https://www.nlsasoccerli.com"},
    {'club_name_raw': "Nm Rapids", 'website': "https://www.nmrapids.org"},
    {'club_name_raw': "Noco", 'website': "https://cityscnoco.com"},
    {'club_name_raw': "Nor'Easters Academy", 'website': "https://www.noreastersacademy.com"},
    {'club_name_raw': "North", 'website': "https://avonlakesoccer.com"},
    {'club_name_raw': "North Branford", 'website': "https://www.nbsoccer.com"},
    {'club_name_raw': "North Brunswick", 'website': "https://www.northbrunswicksoccer.org"},
    {'club_name_raw': "North Carroll", 'website': "https://www.northcarrollsoccer.com"},
    {'club_name_raw': "North Coast Futbol", 'website': "https://petalumasoccer.org"},
    {'club_name_raw': "North Jersey", 'website': "https://www.northjerseyfc.org"},
    {'club_name_raw': "North Jersey Bucks", 'website': "https://northjerseybucks.com"},
    {'club_name_raw': "North Phoenix Christian", 'website': "https://nphxsoccer.org"},
    {'club_name_raw': "North Plainfield", 'website': "https://www.nplainfield.org"},
    {'club_name_raw': "North Star", 'website': "https://www.thebatavian.com"},
    {'club_name_raw': "Northeast", 'website': "https://www.baseball-reference.com"},
    {'club_name_raw': "Northern", 'website': "https://northernillinoissoccerleague.com"},
    {'club_name_raw': "Northern Baltimore", 'website': "https://northernbaltimoreunited.com"},
    {'club_name_raw': "Northern Elite", 'website': "https://www.northernelitesoccer.com"},
    {'club_name_raw': "Northwest", 'website': "https://youthsoccersports.com"},
    {'club_name_raw': "Norwalk Junior", 'website': "https://njsa.org"},
    {'club_name_raw': "Norwich", 'website': "http://www.eccathletics.org"},
    {'club_name_raw': "Nos Santos", 'website': "https://santossc.com"},
    {'club_name_raw': "Npc Futbol & Futsal", 'website': "https://www.msysa.org"},
    {'club_name_raw': "Nvsc", 'website': "https://www.nvscnj.net"},
    {'club_name_raw': "Ny Chelsea", 'website': "http://nychelseafc.com"},
    {'club_name_raw': "Oaks", 'website': "https://vcoaks.com"},
    {'club_name_raw': "Oakwood", 'website': "https://oakwoodsportscenter.org"},
    {'club_name_raw': "Of Guilford", 'website': "https://www.guilfordsoccer.org"},
    {'club_name_raw': "Of Miami Beach", 'website': "https://www.fbssoccer.com"},
    {'club_name_raw': "Of Newington", 'website': "https://www.newingtonsoccer.org"},
    {'club_name_raw': "Of Poughkeepsie", 'website': "https://www.topsc.org"},
    {'club_name_raw': "Ohio", 'website': "https://dublinsoccer.net"},
    {'club_name_raw': "Ohio Galaxies", 'website': "https://www.daytonlocal.com"},
    {'club_name_raw': "Oklahoma Celtic", 'website': "https://oklahomaceltic.com"},
    {'club_name_raw': "Oklahoma Cosmos", 'website': "https://www.southlakessoccer.org"},
    {'club_name_raw': "Old Bridge", 'website': "https://www.oldbridgesc.com"},
    {'club_name_raw': "Oregon Surf", 'website': "https://oregonsurf.org"},
    {'club_name_raw': "Orlando", 'website': "https://www.orlandocitysc.com"},
    {'club_name_raw': "Our Lady Of Perpetual Help", 'website': "https://www.catholicfoundationep.org"},
    {'club_name_raw': "Overland Park", 'website': "https://www.opsoccerclub.org"},
    {'club_name_raw': "Overlea Evolution Futebol", 'website': "http://overleasoccer.org"},
    {'club_name_raw': "Pa Classics Harrisburg", 'website': "https://www.paclassicsharrisburg.com"},
    {'club_name_raw': "Pa Rush", 'website': "https://www.parush.com"},
    {'club_name_raw': "Pacnw", 'website': "https://www.federalwaysoccer.com"},
    {'club_name_raw': "Palacios Futbol", 'website': "https://innovateidaho.org"},
    {'club_name_raw': "Palm Beach", 'website': "https://palmbeachsocceracademyr7111.sportngin.com"},
    {'club_name_raw': "Palm Beach Wolves", 'website': "https://www.pbwfc.com"},
    {'club_name_raw': "Paragon Futbol Academy", 'website': "https://www.paragonfutbol.com"},
    {'club_name_raw': "Park", 'website': "https://soccer-fields.com"},
    {'club_name_raw': "Parkland", 'website': "https://www.cityofparkland.org"},
    {'club_name_raw': "Parsippany", 'website': "https://www.parsippanysoccerclub.org"},
    {'club_name_raw': "Pasadena", 'website': "https://www.pasadenasoccerclub.com"},
    {'club_name_raw': "Pasco", 'website': "https://www.pascosoccer.com"},
    {'club_name_raw': "Pda Scp", 'website': "https://www.pdascp.com"},
    {'club_name_raw': "Penn Academy", 'website': "https://sports.bluesombrero.com"},
    {'club_name_raw': "Penn Express", 'website': "https://tshq.bluesombrero.com"},
    {'club_name_raw': "Pennsauken", 'website': "https://www.pennsaukensoccer.com"},
    {'club_name_raw': "Pennsylvania Prime", 'website': "https://www.pennsylvaniaprimefc.com"},
    {'club_name_raw': "Philadelphia Lone Star", 'website': "https://www.philadelphialonestarfc.com"},
    {'club_name_raw': "Philadelphia Nationals", 'website': "https://ukrainiannationals.teamsnapsites.com"},
    {'club_name_raw': "Philadelphia Ukrainian Nationals", 'website': "https://6abc.com"},
    {'club_name_raw': "Philadelphia Union", 'website': "https://www.bigsoccer.com"},
    {'club_name_raw': "Phoenix Football", 'website': "https://www.carrollmanor.org"},
    {'club_name_raw': "Phoenix Premier", 'website': "https://www.phoenixpremierfc.com"},
    {'club_name_raw': "Phoenix Rising Desert Foothills", 'website': "https://arizona.findsportsusa.com"},
    {'club_name_raw': "Phoenix Rush", 'website': "https://www.phoenixrushsoccer.com"},
    {'club_name_raw': "Phoenix Valley", 'website': "https://www.phoenixvalleysoccerclub.com"},
    {'club_name_raw': "Pima County Surf", 'website': "https://pimacountysurf.com"},
    {'club_name_raw': "Piscataway", 'website': "https://www.piscatawaysoccer.org"},
    {'club_name_raw': "Pittsburgh Riverhounds", 'website': "https://www.riverhounds.com"},
    {'club_name_raw': "Pittsgrove", 'website': "https://pittsgrovesoccer.com"},
    {'club_name_raw': "Placer", 'website': "https://www.placerunited.com"},
    {'club_name_raw': "Plainfield", 'website': "https://plainfieldyouthpanthers.com"},
    {'club_name_raw': "Plainville", 'website': "https://www.plainvillesoccer.com"},
    {'club_name_raw': "Plant", 'website': "https://plantcityyouthsoccer.com"},
    {'club_name_raw': "Plantation .", 'website': "https://www.nfhsnetwork.com"},
    {'club_name_raw': "Player Technique Academy", 'website': "https://ptasoccer.com"},
    {'club_name_raw': "Playmaker Futbol Academy", 'website': "https://www.playmakerfutbolacademy.com"},
    {'club_name_raw': "Pleasanton Rage", 'website': "https://pleasantonrageuslw.org"},
    {'club_name_raw': "Polar Vortex", 'website': "https://www.polarvortexfc.com"},
    {'club_name_raw': "Pomperaug", 'website': "https://www.pomperaugwarriors.com"},
    {'club_name_raw': "Port Orange", 'website': "https://www.port-orange.org"},
    {'club_name_raw': "Port St. John", 'website': "https://psjsoccerclub.wordpress.com"},
    {'club_name_raw': "Portage", 'website': "https://portagesoccer.com"},
    {'club_name_raw': "Portland", 'website': "https://www.heartsofpine.com"},
    {'club_name_raw': "Portland Thorns", 'website': "https://www.thorns.com"},
    {'club_name_raw': "Prattville", 'website': "https://www.coacht.com"},
    {'club_name_raw': "Prestige", 'website': "https://ourcitysc.com"},
    {'club_name_raw': "Pride", 'website': "https://fcpride.org"},
    {'club_name_raw': "Pride Elite", 'website': "https://cdn1.sportngin.com"},
    {'club_name_raw': "Prime Miami", 'website': "https://www.fc-prime.com"},
    {'club_name_raw': "Princeton", 'website': "https://princetonsocceracademy.com"},
    {'club_name_raw': "Prior Lake", 'website': "https://www.priorlakefootball.com"},
    {'club_name_raw': "Pro Alliance", 'website': "https://www.proalliancefc.com"},
    {'club_name_raw': "Progressive", 'website': "http://progressivesoccertraining.com"},
    {'club_name_raw': "Project 208", 'website': "https://www.project208fc.org"},
    {'club_name_raw': "Psa Football", 'website': "https://www.psaplano.org"},
    {'club_name_raw': "Pvsc", 'website': "https://pvscunited.com"},
    {'club_name_raw': "Q World", 'website': "https://qworldsoccer.com"},
    {'club_name_raw': "Quick Touch Futbol", 'website': "https://www.quicktouchfutbol.com"},
    {'club_name_raw': "Radnor", 'website': "https://www.radnorsoccerclub.org"},
    {'club_name_raw': "Ramapo Valley", 'website': "https://rvsoccer.sportngin.com"},
    {'club_name_raw': "Rancho Challenge", 'website': "https://www.ranchochallengefc.org"},
    {'club_name_raw': "Rancocas Valley", 'website': "https://www.rvsoccerclub.org"},
    {'club_name_raw': "Rangers", 'website': "https://fullertonrangers.demosphere-secure.com"},
    {'club_name_raw': "Reading Rage Surf", 'website': "https://public.totalglobalsports.com"},
    {'club_name_raw': "Real", 'website': "https://realsoccerclub.org"},
    {'club_name_raw': "Real Arizona", 'website': "https://www.realarizonafc.org"},
    {'club_name_raw': "Real Athletic Development", 'website': "https://radfc.sportngin.com"},
    {'club_name_raw': "Real Colorado Academy", 'website': "https://www.realcolorado.net"},
    {'club_name_raw': "Rebels Academy", 'website': "https://futbolrebels.com"},
    {'club_name_raw': "Red Bank", 'website': "https://redbank-fc.org"},
    {'club_name_raw': "Reisterstown", 'website': "https://reisterstownrec.com"},
    {'club_name_raw': "Renegades", 'website': "https://www.renegadesfootballclub.org"},
    {'club_name_raw': "Rham", 'website': "https://www.rhamyouthsoccer.org"},
    {'club_name_raw': "Rheems Athletic Association", 'website': "https://www.rheemsaa.org"},
    {'club_name_raw': "Rhode Island Surf", 'website': "https://runsignup.com"},
    {'club_name_raw': "Richmond", 'website': "https://soccer.exposureevents.com"},
    {'club_name_raw': "Ridgefield Football", 'website': "https://rhsfootball.teamsnapsites.com"},
    {'club_name_raw': "Ridley", 'website': "http://ridleyhsfootball.com"},
    {'club_name_raw': "Rise", 'website': "https://www.risesc.org"},
    {'club_name_raw': "River Dell Blackhawks", 'website': "https://riverdellblackhawks.com"},
    {'club_name_raw': "Rockville Centre", 'website': "https://soccerretailers.com"},
    {'club_name_raw': "Rocky", 'website': "https://www.thesportsbank.net"},
    {'club_name_raw': "Rohnert Park", 'website': "https://rpsoccerclub.org"},
    {'club_name_raw': "Roselle Park", 'website': "https://www.roselleparksoccer.com"},
    {'club_name_raw': "Roseville", 'website': "https://rosevillesoccer.com"},
    {'club_name_raw': "Rps Academy", 'website': "https://rpsacademies.com"},
    {'club_name_raw': "Rsl Royals West", 'website': "https://www.rslroyalswest.com"},
    {'club_name_raw': "Rsl-Az Anthem", 'website': "https://www.rsl-azanthem.com"},
    {'club_name_raw': "Rsl-Az West Valley", 'website': "https://rslazwestvalley.org"},
    {'club_name_raw': "Rumson Futbol", 'website': "https://www.rumsonfc.com"},
    {'club_name_raw': "Rush Union", 'website': "https://www.rushunionsoccer.org"},
    {'club_name_raw': "Rysa Wildcats", 'website': "https://www.rysawildcats.com"},
    {'club_name_raw': "Sac/Ba", 'website': "https://www.sackick.com"},
    {'club_name_raw': "Sachem Slammers", 'website': "https://www.sysl.org"},
    {'club_name_raw': "Sacramento", 'website': "https://www.sacunited.com"},
    {'club_name_raw': "Safc", 'website': "https://lonestar-sc.com"},
    {'club_name_raw': "Salisbury", 'website': "https://acsalisbury.com"},
    {'club_name_raw': "Salone", 'website': "https://whnt.com"},
    {'club_name_raw': "Salvo", 'website': "https://goalgalaxymn.com"},
    {'club_name_raw': "San Antonio", 'website': "https://www.saunitedsoccer.com"},
    {'club_name_raw': "San Diego Surf", 'website': "https://surfsoccer.com"},
    {'club_name_raw': "San Francisco Elite", 'website': "https://www.sfelitesc.org"},
    {'club_name_raw': "San Joaquin", 'website': "http://www.cysad8.org"},
    {'club_name_raw': "Sandy Spring", 'website': "https://www.sandyspringsoccer.org"},
    {'club_name_raw': "Santa Ana", 'website': "https://goldencityfc.wordpress.com"},
    {'club_name_raw': "Santa Barbara", 'website': "https://santabarbarasc.org"},
    {'club_name_raw': "Santa Clara Sporting", 'website': "https://www.santaclarasporting.com"},
    {'club_name_raw': "Santa Rosa", 'website': "https://soccerandsports.com"},
    {'club_name_raw': "Savannah Select", 'website': "https://www.cgsasoccer.org"},
    {'club_name_raw': "Sb4U Academy", 'website': "https://sb4u.sportngin.com"},
    {'club_name_raw': "Scarsdale", 'website': "https://www.scarsdalesoccer.net"},
    {'club_name_raw': "Scorpions South", 'website': "https://www.scorpionssoccer.org"},
    {'club_name_raw': "Seacoast", 'website': "https://seacoastunited.com"},
    {'club_name_raw': "Seacoast Nh", 'website': "https://www.hyasports.org"},
    {'club_name_raw': "Seattle", 'website': "https://www.soundersfc.com"},
    {'club_name_raw': "Seattle Celtic", 'website': "https://www.wpl-soccer.com"},
    {'club_name_raw': "Seattle Reign Academy", 'website': "https://www.reignacademy.com"},
    {'club_name_raw': "Select North", 'website': "https://selectma.com"},
    {'club_name_raw': "Sf Glens", 'website': "https://www.sfglensacademy.com"},
    {'club_name_raw': "Sffa", 'website': "https://sffada.com"},
    {'club_name_raw': "Sheriffs", 'website': "https://www.inplay.org"},
    {'club_name_raw': "Shoals", 'website': "https://www.shoalssoccerclub.org"},
    {'club_name_raw': "Shore", 'website': "https://espremiersoccer.com"},
    {'club_name_raw': "Sierra Vista", 'website': "https://sierravistasoccerleague.org"},
    {'club_name_raw': "Simmons", 'website': "https://www.simmons-soccer.com"},
    {'club_name_raw': "Sj Futbol", 'website': "https://www.southjerseyfutbol.com"},
    {'club_name_raw': "Sjys", 'website': "https://home.sjgsl.org"},
    {'club_name_raw': "Skylands", 'website': "https://www.skylandssoccerclub.com"},
    {'club_name_raw': "Slsg Illinois", 'website': "https://www.slsgsoccer.com"},
    {'club_name_raw': "Snohomish", 'website': "https://snocofc.com"},
    {'club_name_raw': "So Cal Blues", 'website': "https://www.scblues.com"},
    {'club_name_raw': "Soca Elite", 'website': "https://www.socaspot.org"},
    {'club_name_raw': "Socal", 'website': "https://socalpitch.com"},
    {'club_name_raw': "Socal Elite", 'website': "https://socalelitefc.com"},
    {'club_name_raw': "Soccer4Life", 'website': "https://soccer4life.org"},
    {'club_name_raw': "Solar", 'website': "https://www.trophyclub.org"},
    {'club_name_raw': "Solar Academy", 'website': "https://solarsoccerclub.net"},
    {'club_name_raw': "Soma", 'website': "https://www.somafc.org"},
    {'club_name_raw': "Somers", 'website': "https://www.somerssoccerassociation.org"},
    {'club_name_raw': "Sonoita-Elgin", 'website': "https://southernarizonaguide.com"},
    {'club_name_raw': "Sonora", 'website': "https://www.sonoranfoothillssoccerleague.com"},
    {'club_name_raw': "South Brunswick", 'website': "https://sbscintown.sportngin.com"},
    {'club_name_raw': "South Carolina", 'website': "https://www.southcarolinaunitedfc.com"},
    {'club_name_raw': "South Carolina Surf", 'website': "https://static1.squarespace.com"},
    {'club_name_raw': "South River Athletics", 'website': "https://southriverathletics.net"},
    {'club_name_raw': "South Valley", 'website': "https://www.southvalleychivas.com"},
    {'club_name_raw': "Southeast", 'website': "http://www.secjsa.org"},
    {'club_name_raw': "Southington", 'website': "https://www.southingtonsoccer.org"},
    {'club_name_raw': "Southwest", 'website': "https://southwestsc.sportngin.com"},
    {'club_name_raw': "Space Coast", 'website': "https://www.spacecoastsoccer.org"},
    {'club_name_raw': "Spartans", 'website': "https://www.azspartans.com"},
    {'club_name_raw': "Spokane Shadow", 'website': "https://washingtonyouthsoccer.org"},
    {'club_name_raw': "Sportfriends", 'website': "https://sportfriendssc.org"},
    {'club_name_raw': "Sporting", 'website': "https://www.sportingkc.com"},
    {'club_name_raw': "Sporting Columbus", 'website': "https://www.kidslinked.com"},
    {'club_name_raw': "Sporting Ct", 'website': "https://sportingct.com"},
    {'club_name_raw': "Sporting Iowa", 'website': "https://members.dsmpartnership.com"},
    {'club_name_raw': "Sporting Kaw Valley", 'website': "https://www.sportingkv.com"},
    {'club_name_raw': "Sporting Nebraska", 'website': "https://www.sportingnebraskafc.com"},
    {'club_name_raw': "Sporting New Jersey", 'website': "https://www.sportingac.com"},
    {'club_name_raw': "Sporting Oklahoma", 'website': "https://www.sportingok.com"},
    {'club_name_raw': "Sporting Slammers", 'website': "https://sportingslammers.com"},
    {'club_name_raw': "Sporting Springfield", 'website': "https://www.springfieldsportsclub.com"},
    {'club_name_raw': "Sporting Tallahassee", 'website': "https://www.tallahasseesoccer.com"},
    {'club_name_raw': "Sporting Wichita", 'website': "https://www.sportingwichita.net"},
    {'club_name_raw': "Springfield", 'website': "https://springfield-fc.org"},
    {'club_name_raw': "Springs", 'website': "https://www.tamaracsocceracademy.com"},
    {'club_name_raw': "St. Louis Development Academy", 'website': "https://www.stlouisda.com"},
    {'club_name_raw': "St. Mary'S", 'website': "https://smcmathletics.com"},
    {'club_name_raw': "St. Petersburg", 'website': "https://www.visitstpeteclearwater.com"},
    {'club_name_raw': "St23", 'website': "https://www.st23academy.com"},
    {'club_name_raw': "Sta Mount Olive", 'website': "https://www.stasoccer.org"},
    {'club_name_raw': "Stafford Springs", 'website': "https://www.si.com"},
    {'club_name_raw': "Stamford", 'website': "https://www.chelseapiers.com"},
    {'club_name_raw': "Stanislaus", 'website': "https://www.stanislaus-united.org"},
    {'club_name_raw': "Stars", 'website': "https://soccerstars.com"},
    {'club_name_raw': "State 48", 'website': "https://azgoldcup.com"},
    {'club_name_raw': "Stateline", 'website': "https://statelinesc.com"},
    {'club_name_raw': "Staten Island", 'website': "https://www.statenislandsoccerclub.org"},
    {'club_name_raw': "Sterling", 'website': "https://sterlingsoccerclub.org"},
    {'club_name_raw': "Stetson Fa", 'website': "https://www.stetsonfutbolassociation.com"},
    {'club_name_raw': "Sting", 'website': "https://www.texassoccerfields.com"},
    {'club_name_raw': "Sting Austin", 'website': "https://austin.stingsoccer.com"},
    {'club_name_raw': "Stl Football", 'website': "https://www.etsy.com"},
    {'club_name_raw': "Stonington", 'website': "https://www.stoningtonsoccerclub.com"},
    {'club_name_raw': "Strikers", 'website': "https://strikersnisa.sportzstudio.com"},
    {'club_name_raw': "Strikers Futbol Academy", 'website': "https://strikersfutbolhoboken.squarespace.com"},
    {'club_name_raw': "Strikers Miami", 'website': "https://www.strikersmiami.com"},
    {'club_name_raw': "Suffield", 'website': "https://www.suffieldsoccer.com"},
    {'club_name_raw': "Sugar Land", 'website': "http://www.sugarlandsoccer.org"},
    {'club_name_raw': "Summit", 'website': "https://thesummitleague.org"},
    {'club_name_raw': "Sun Warriors Azfc", 'website': "https://sunwarriorsazfc.wixsite.com"},
    {'club_name_raw': "Sunrise", 'website': "https://sunrisesurfsoccer.com"},
    {'club_name_raw': "Sunset", 'website': "https://www.sunsetfc.com"},
    {'club_name_raw': "Superstars", 'website': "https://www.soccersuperstars.org"},
    {'club_name_raw': "Susa Academy", 'website': "https://www.susaacademy.com"},
    {'club_name_raw': "Susa Northeast", 'website': "https://soccerzoneusa.com"},
    {'club_name_raw': "Susquehanna Football", 'website': "https://www.susquehannafootballclub.com"},
    {'club_name_raw': "Tampa Bay", 'website': "https://www.tampabayclubsport.com"},
    {'club_name_raw': "Tbaa", 'website': "https://tbaa.net"},
    {'club_name_raw': "Team Challenger North", 'website': "https://www.localgymsandfitness.com"},
    {'club_name_raw': "Tennessee", 'website': "https://www.tnsoccer.org"},
    {'club_name_raw': "Terryville", 'website': "https://greatnonprofits.org"},
    {'club_name_raw': "Teton", 'website': "https://www.tetontekkers.com"},
    {'club_name_raw': "The Academy Of Central Florida", 'website': "https://theacademycfl.com"},
    {'club_name_raw': "The St. James Football", 'website': "https://www.loudounnow.com"},
    {'club_name_raw': "Tigres", 'website': "https://www.foxsports.com"},
    {'club_name_raw': "Titanes", 'website': "https://us.soccerway.com"},
    {'club_name_raw': "Tko Premier", 'website': "https://tkopremier.org"},
    {'club_name_raw': "Toca Juniors", 'website': "https://www.tocajuniors.com"},
    {'club_name_raw': "Tolland", 'website': "https://www.zeffy.com"},
    {'club_name_raw': "Toms River", 'website': "https://www.tomsriverfc.com"},
    {'club_name_raw': "Top Level Futbol", 'website': "https://www.toplevelfutbol.com"},
    {'club_name_raw': "Topton", 'website': "https://toptonfga.com"},
    {'club_name_raw': "Towson", 'website': "https://www.towsonclubsoccer.com"},
    {'club_name_raw': "Towsontowne", 'website': "https://towsontownesoccer.com"},
    {'club_name_raw': "Trenton", 'website': "https://www.trentoncitysc.com"},
    {'club_name_raw': "Triangle", 'website': "https://tyul.usetopscore.com"},
    {'club_name_raw': "Triumph", 'website': "https://www.greenvilletriumph.com"},
    {'club_name_raw': "Tru Tekkers", 'website': "https://www.trutekkers.com"},
    {'club_name_raw': "Tucson Elite", 'website': "https://www.taxexemptworld.com"},
    {'club_name_raw': "Tucson Mountains", 'website': "https://tucsonmountainsoccerclub.com"},
    {'club_name_raw': "Tulsa", 'website': "https://www.fctulsa.com"},
    {'club_name_raw': "Tulsa Academy", 'website': "https://www.blitzacademyfc.com"},
    {'club_name_raw': "Tupelo", 'website': "https://tupelofc.org"},
    {'club_name_raw': "Two Rivers", 'website': "https://www.tworiverssoccer.com"},
    {'club_name_raw': "U.S. Futsal", 'website': "https://futsal.com"},
    {'club_name_raw': "Union", 'website': "https://www.unionscnj.com"},
    {'club_name_raw': "Union 10", 'website': "https://union10fcbaldwincounty.com"},
    {'club_name_raw': "Union Kc Red", 'website': "https://www.wpslsoccer.com"},
    {'club_name_raw': "Uniondale", 'website': "https://uniondalesoccer.clinicsandcamps.com"},
    {'club_name_raw': "Upper 90", 'website': "https://www.upper90futbolclub.com"},
    {'club_name_raw': "Usa Elite Academy", 'website': "https://www.usaelitefc.com"},
    {'club_name_raw': "Utah", 'website': "https://sports.deseret.com"},
    {'club_name_raw': "Utah Surf", 'website': "https://utahsurfsoccer.com"},
    {'club_name_raw': "Va Rush", 'website': "http://www.varushboosterclub.com"},
    {'club_name_raw': "Vale Sports", 'website': "https://valesc.com"},
    {'club_name_raw': "Valencia", 'website': "https://fcvalencia.com"},
    {'club_name_raw': "Valencia Academy", 'website': "https://www.valenciacfacademy-seattle.com"},
    {'club_name_raw': "Valley", 'website': "https://valleyfcct.com"},
    {'club_name_raw': "Valley Surf", 'website': "https://www.valleysurf.org"},
    {'club_name_raw': "Valor", 'website': "https://www.valorsoccer.com"},
    {'club_name_raw': "Verde Valley", 'website': "https://www.azarsenalsc.org"},
    {'club_name_raw': "Vereinigung Erzgebirge", 'website': "https://vesoccer.demosphere-secure.com"},
    {'club_name_raw': "Vernon", 'website': "https://www.vernonsoccerclub.org"},
    {'club_name_raw': "Vero", 'website': "https://www.verofc.org"},
    {'club_name_raw': "Vienna", 'website': "https://www.vys.org"},
    {'club_name_raw': "Vikings", 'website': "https://www.vikingsfc.org"},
    {'club_name_raw': "Vineland Sa", 'website': "https://www.vinelandsoccer.com"},
    {'club_name_raw': "Virginia", 'website': "https://www.virginiavalorfc.org"},
    {'club_name_raw': "Virginia Velocity", 'website': "https://virginiavelocity.net"},
    {'club_name_raw': "Wake", 'website': "https://nzonesports.com"},
    {'club_name_raw': "Warminster", 'website': "https://warminstersoccerclub.com"},
    {'club_name_raw': "Warner", 'website': "https://www.warnersoccer.com"},
    {'club_name_raw': "Warwick", 'website': "https://warwicksoccer.com"},
    {'club_name_raw': "Wasatch", 'website': "https://www.yellowpages.com"},
    {'club_name_raw': "Washington Capital", 'website': "https://www.wcunited.org"},
    {'club_name_raw': "Watertown", 'website': "https://www.watertownyouthsoccer.net"},
    {'club_name_raw': "Wave", 'website': "https://wavesoccer.org"},
    {'club_name_raw': "Waves", 'website': "https://www.wavessoccer.com"},
    {'club_name_raw': "Wayne", 'website': "https://www.waynenjsoccer.org"},
    {'club_name_raw': "Wellington", 'website': "https://www.wellingtonsoccer.com"},
    {'club_name_raw': "Wenatchee", 'website': "https://wenatcheeunitedsc.com"},
    {'club_name_raw': "West Covina", 'website': "https://www.wcysc.com"},
    {'club_name_raw': "West Deptford", 'website': "https://www.wdgscamps.com"},
    {'club_name_raw': "West Essex", 'website': "https://www.westessexfc.com"},
    {'club_name_raw': "West Florida Flames", 'website': "https://fcflames.com"},
    {'club_name_raw': "West Morris", 'website': "https://www.westmorrissoccer.org"},
    {'club_name_raw': "West New York", 'website': "https://www.westnewyorknj.org"},
    {'club_name_raw': "West Orange", 'website': "https://www.westorangeathletics.com"},
    {'club_name_raw': "West Pines", 'website': "https://westpinesunited.org"},
    {'club_name_raw': "West Virginia Futbol", 'website': "https://westvirginiafutbolclub.com"},
    {'club_name_raw': "Westchester Flames", 'website': "https://westchesterflames.com"},
    {'club_name_raw': "Wethersfield George D Ritchie", 'website': "https://www.wethersfieldsoccer.com"},
    {'club_name_raw': "Wheaton", 'website': "https://www.wheatonunited.net"},
    {'club_name_raw': "Whitpain Recreation Assoc", 'website': "https://elementaryconnections.com"},
    {'club_name_raw': "Wichita", 'website': "https://www.aztecaacademywichita.com"},
    {'club_name_raw': "Wilmington Hammerheads", 'website': "https://www.uslleaguetwo.com"},
    {'club_name_raw': "Windsor", 'website': "https://www.windsorsoccer.org"},
    {'club_name_raw': "Windsor Locks", 'website': "https://windsorlocksct.org"},
    {'club_name_raw': "Winter Haven", 'website': "https://www.winterhavensoccerclub.com"},
    {'club_name_raw': "Winter Park", 'website': "https://www.ironpitchsoccergym.com"},
    {'club_name_raw': "World Class Premier", 'website': "https://www.worldclasspremier.net"},
    {'club_name_raw': "Wtsc", 'website': "https://wtsoccer.net"},
    {'club_name_raw': "Wyomissing Area", 'website': "https://www.wyoareasoccerclub.org"},
    {'club_name_raw': "Xafc Nj", 'website': "https://xafcnj.com"},
    {'club_name_raw': "Xplosion", 'website': "https://www.xplosionsc.com"},
    {'club_name_raw': "Yavapai", 'website': "https://yavapaisoccer.com"},
    {'club_name_raw': "Yorktown", 'website': "https://www.yorktownsoccer.org"},
    {'club_name_raw': "Yuma", 'website': "https://yumayouthsoccer.gotsportsites.com"},
    {'club_name_raw': "Yuriria", 'website': "https://yuriria-supermarket.wheree.com"},
]
